/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRANSFER_H_RPCGEN
#define _TRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct file_data {
	char *filename;
	struct {
		u_int content_len;
		char *content_val;
	} content;
	int bytes_sent;
};
typedef struct file_data file_data;

#define TRANSFER_PROG 0x31230000
#define TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define UPLOAD_FILE 1
extern  int * upload_file_1(file_data *, CLIENT *);
extern  int * upload_file_1_svc(file_data *, struct svc_req *);
extern int transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UPLOAD_FILE 1
extern  int * upload_file_1();
extern  int * upload_file_1_svc();
extern int transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_data (XDR *, file_data*);

#else /* K&R C */
extern bool_t xdr_file_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRANSFER_H_RPCGEN */
